name: Pipeline de Testes de API - Rest Assured & Java 21

on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    name: Execução Automatizada da Suíte de Testes
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Configurar Java 21 (JDK Temurin)
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: 3. Executar Testes Automatizados (Surefire)
        run: mvn clean test --batch-mode

      - name: 4. Publicar Relatório de Testes (Surefire Reports)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-surefire
          path: target/surefire-reports/

      - name: 5. Gerar Relatório Allure
        if: always()
        run: mvn allure:report

      - name: 6. Publicar Relatório Allure no GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/site/allure-maven-plugin
